# Generated by Django 5.1.4 on 2025-01-06 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashlocation',
            name='users_joined',
            field=models.ManyToManyField(blank=True, related_name='joined_locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
